### ISSUE TITLE
[Meta] Make Contributing Easier

### ISSUE THREAD

**Issue by fubuloubu** [ethereum/vyper#1458]
In the last call (#1419) we talked about ways to make it easier to contribute, and streamline the release process for new versions of the compiler. This issue is for discussions different ideas for doing this.

- [ ] Moving "Principles and Goals" to a separate document
- [ ] Expanding on contributions
- [ ] Documenting the release process (for future maintainers)
