### ISSUE TITLE
Improving Documentation

### ISSUE THREAD

**Issue by chgue** [ethereum/vyper#393]
### What's your issue about?

The documentation is lacking at the moment and is needed for the audit (see #390).

### How can it be fixed?

As a starting point I would propose to emulate the [Solidity documentation](https://solidity.readthedocs.io/) and hopefully get the Viper documentation to a certain feature parity.

Some chapters to add/improve:

~- [ ] Introduction to Smart Contracts (Very similar to Solidity)~
- [ ] Security Considerations (Very similar to Solidity)
- [x] Testing strategy (Currently dead link in readme)
- [ ] Viper in Depth (Very basic at the moment, priority)
~- [ ] Style Guide (PEP 0008-like?)~ removed, can always be brought in later.
- [x] Contributing #422
- [x] Viper in Depth -- Types
- [x] Viper by example (See /examples) @NedYork #418
- [x] Installing Viper (Add Docker and viper.tools mention) #400
- [x] Compiling (Move from readme to documentation) #400 
- [x] Index/Landing Page #400 
- [x] Principles and Goals (Move from readme to documentation?) #400

I will probably start working on some of these in the next few days. Please let me know what you think and if you would suggest any other chapters to be added. 

In order to avoid duplicate work please post below if you are working on anything at the moment and I will edit the list above to reflect that.

#### Cute Animal Picture
Dogumentation is important!<sup><sup>sorry</sup></sup>
![](http://i.barkpost.com/wp-content/uploads/2015/08/o-DOG-READING-A-BOOK-facebook.jpg?q=70&fit=crop&crop=entropy&w=808&h=500)

**Comment by NedYork** [comment]
I'm currently working on the 'Viper by example' section. Will keep you updated.

**Comment by amitkumarj441** [comment]
@chgue Add `Contributions Guideline` in above list and initiated PR #422 for this.

**Comment by fubuloubu** [comment]
@DavidKnott how many of the items he mentions above truly deficient?

**Comment by DavidKnott** [comment]
I'd say what's missing up there is about right.

**Comment by fubuloubu** [comment]
Docs for "Introduction to Smart Contracts" I would claim as out of scope. Let's make the assumption you know a little bit about what they are, and now you want to know how to write them. There are so many articles on "what are smart contracts" already.

The doc on "Security Considerations" I would claim needs to be included if there are unsafe patterns we cannot protect against. What currently exists for this?

A doc for "Testing strategy" was originally meant as an organizational document for specifically how you should write tests for Vyper and should go under a "contributing" section. The wider doc on "how do you test smart contracts" is a bit out of scope for this compiler.

All three of these we can also link to "Consensys Best Practices" or the SecurEth guidelines (when they are complete) for more information.

**Comment by fubuloubu** [comment]
"Vyper in Depth" should probably be polished up. I know we have a lot there already.

"Style Guide" can just link to PEP8. I wonder how that would work directly applied to Vyper code?

**Comment by jacqueswww** [comment]
Closing, any additional required docs can be placed in separate tickets. But this is just too old to keep open / be relevant.
