### ISSUE TITLE
Meeting 4th June 2018

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#862]
## General Bi-Weekly meeting.
Start: Monday 1st June 2018, 14:00 UTC (https://time.is/UTC)
Hangouts: https://meet.google.com/czc-kuep-jda

### Agenda
- Logo Bounty Finalisation (#794)
- Issues that have to be complete before tagging, first beta candidate:
  - [x] #852 Add pragma tag
  - [x] #770 Static call per method
  - [ ] #781 Fallback/Default function
