### ISSUE TITLE
Adopt NatSpec

### ISSUE THREAD

**Issue by fulldecent** [ethereum/vyper#898]
Adopt NatSpec for function definitions.

NatSpec is documented here https://github.com/ethereum/wiki/wiki/NatSpec-Determination and it is perfectly applicable to vyper.

The a of vyper is: "Vyper code should be maximally human-readable."

Presently it is difficult to grok functions because you may need to read all the code to see how the parameter is used. With natspec you can document all function parameters.

If NacSpec is adopted, it should be added for all functions in https://github.com/ethereum/vyper/tree/master/examples

**Comment by fubuloubu** [comment]
I'm on board with this.

We were talking about our version tag being a natspec comment at the top of the file, and I have a new scheme for tracking requirements and implementation of those requirements in-file described [here](https://guidelines.secureth.org/development/traceability) that involves two new natspec tags `@req # [text]` and `@imp # [note]` so you can generate requirements traceability for a given file for auditing purposes.

**Comment by fubuloubu** [comment]
There is also [radspec](https://github.com/aragon/radspec) which is "Rad" :metal:

**Comment by jacqueswww** [comment]
Good idea, along side this issue I would suggest noting natspec in the documentation. And also consider adding natspec annotations to any larger examples in the docs.

**Comment by fulldecent** [comment]
Always follow best practices in the examples!

I have been helping with Solidity and getting their examples up-to-date. I can help with this issue if you tell me a PR would be welcome.

It would be a good way for me to learn more.

# Work plan

- [ ] Add NatSpec to documentation, somewhere in https://vyper.readthedocs.io/en/latest/vyper-by-example.html?highlight=sender
- [ ] Identify all examples where documentation is appropriate
- [ ] Add NatSpec to those places
- [ ] Identify external stakeholders (like https://vyper.online) and ask them to update in step

**Comment by jacqueswww** [comment]
Great stuff 👌👍
