### ISSUE TITLE
Meeting 18th June 2018

### ISSUE THREAD

**Issue by jacqueswww** [ethereum/vyper#907]
## General Bi-Weekly meeting.
Start: Monday 18th June 2018, 14:00 UTC (https://time.is/UTC)
Hangouts: https://meet.google.com/czc-kuep-jda

### Agenda
-  Update on logo bounty (#794)
- VIPs / Issues to discuss
  - [ ] VIP: reduce the cost and difficulty of code reuse in common situations #901 
  - [ ] Allow default parameters #903 / #884
  - [ ] First phase reason string support #889 
  - [ ] VIP: Interfaces #885 
  - [ ] Adding source map  #878
  - [ ] CamelCase built in constants? #843 
  - [ ] NatSpec https://github.com/ethereum/vyper/issues/898 
  - [x] Report back to ERC721

**Comment by ben-kaufman** [comment]
Any important notes from the meeting?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jacqueswww** [comment]
@ben-kaufman Just click through the specific issues to see the exact decisions. - Most were items were accepted. With the exception of #901 which is quite a large change, and we left it for further deliberation.
With approving of default parameters #904, we don't have a conflict to implement ERC721, and came to the conclusion that it's a good trade of for a vyper developer (we keep not allowing function overloading, but allow a very secific case that is easy to understand -> has one function in the code).
